- name: Upgrade system
  apt: upgrade=dist update_cache=yes

# Install dependecies
- name: Install dependencies
  apt: name={{ item }} state=present
  with_items:
    - man
    - vim
    - tmux
    - zsh
    - git
    - curl
    - wget
    - sudo
    - ca-certificates
    - build-essential
    - nodejs
    - npm
    - dnsutils
    - locales
    - locales-all

- name: Ensure fr_FR locale exists
  locale_gen: name=fr_FR.UTF-8 state=present

